### ISSUE TITLE
Compile issue during npm install

### ISSUE THREAD

**Issue by lobo235** [bitfloor/trader.nodejs#2]
I ran into an issue while trying to install the btctrader (trader.nodejs) module. When npm tries to compile node-decimal it fails with an error and the whole process aborts. I took a look at the node-decimal project on github and noticed in their readme the following line:

> You will need libgmp3 development package installed to install node-decimal. On debian systems this is the libgmp3-dev package

I'm using Ubuntu so I installed the libgmp3-dev package using the following command which fixed the problem for me:

``` bash
sudo apt-get install libgmp3-dev
```

I wanted to take time to post this here in the issues for this project in case anyone else runs into this problem.

**Comment by defunctzombie** [comment]
I have updated the package to use a new fixed decimal library which does not require compilation. The decimal library used before is now deprecated in favor of this pure js num library.

Thank you for the detailed post tho :)
